language: java
addons:
  sonarcloud:
    organization: lonesocket-github
    branches:
    - master
    - develop
    token:
      secure: vX2jiKcWyA0YpRiQXQNHMQvmcfl8udaH5sIkw1JVoRNfDaghJHoRcJIkCPIztukeMEDYfCJPmcwa8r3WOLFfWQti6YkRnstzG9gBP8qsBGs6ozwtgSaDj+R2dlAi9ENaWuAuYcqq1vashL/Uk1NBkbOOoIPk+rCLOjK6s0erlABfBB9pDTUIKFfhur/HQSJ98pnI0KLHDaaAuT9n1QzknvWuFd8uLt8J4H7lLj/5fafabyyvVaNn+BY9SqGSiALqOZZFfC4FRjBKgYkYYu4TDkreFrI5euNMZlA7W8/+sIRCB0AiDf3moz9UlvnP4GHddXCvI1H2OIhCEMD7z14aWMldHM4woB9QCB2h6oOsQL5VGHqnCuI1JGDOq4rQDoApcQFkj+j2d6cl3dHCCcJ2ZB3lxV/UjtCSUGaBeEk05f43jQ07chJWYGkLGNm7luvRhHXVJrO1hk/6F2whHcratEbRUhMDE6MEOdsRnzx6TXcIpp7EjOOA2eTmYHnxba13Cu8MJN7/sNkcEDhfADWhj5t7VKiqp48caoQwlUkhuLJhG0WDJz2Mlu5XgcevKJhbmAMq4j3TKxI/Zj/CTGG+s2GFgu6laJiz7heQ+4yGHoPfJVXWkwhEyIg1olg2/dUhTwa5KxCjmjtx1Hr0fNiL06u+/W+TReeN2LESSY+DLDE=
script:
- "./gradlew sonarqube"
notifications:
  slack:
    secure: EoghbMQklb94Mozqxwm+oaNxOnETjP3snwea2daosgzYl5sn4dHf6IbiLN1vYU13ZTH+z+WXP4woHO2Y9RMJe6fmkkIvNp849N1E6ALbYrBJGd3CeVXhdDXsuS2mbW+aeJweqpG1m05NqSCIQqlghpeXlK2hOLdHBX3NvzSRT2rMGPFPqwP72EIuwRUBrML7/WbJWExpCeDXkCcUbfm+ZvjFdxJyVviTUPh7f/iAl6eFz8JnZRpqexy96fjO4mMK4weTfGba+sFB/EkTInYS4Rkss3E5LcEzeeWvHTNPrw3pmbnulzLw69lbhRhIXX0/Iuk1AfeWY8m7uNQFEsw47mhGWonkGdAcT7TG1YhBVP1MUZlzJN6xerPU22g4TeaJ5ttAGV21pdpoIvglRrysJITlvQtVejyJAjIr7WL7wiPYjk3cSQH8Lwz3nu2sNuN0PqVNiccr3lAOsHc8mE30PBTDFGYJx2r7zrqvbhSbGPgm6QoMsNMC58oyX41RVjwsqFmQjCGwr6jnhQhXZwaS8UpclwqbTlwDtpDahXaykrmzK93MNNL2lA+blAyoKqRhes119R04pWPN6VYoCQMV2j35u/Gl4Vscm07AN/x9ptmW1YDYshDsiOXNYoJqI+sVO9eWHknAOQqZrYUsJ14fhXJK8Uk1a0dST/w63w7Osn4=
